version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: balances
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    command: celery -A app.core.task.app3 beat --loglevel=info
    depends_on:
      - redis
      - web

  celeryw:
    build: .
    command: celery -A app.core.task.app3 worker --loglevel=info
    depends_on:
      - redis
      - web